FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json ./
RUN npm install
EXPOSE 3000
ENV WATCHPACK_POLLING=true NODE_ENV=development
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
